LoadModule mpm_event_module modules/mod_mpm_event.so

LoadModule authz_core_module modules/mod_authz_core.so
LoadModule dir_module modules/mod_dir.so

LoadModule unixd_module modules/mod_unixd.so
LoadModule log_config_module modules/mod_log_config.so

Listen 8081

<VirtualHost *:8081>
    ServerName wegone.site.lan
    ServerAlias wegone.localhost
    DocumentRoot "/usr/local/apache2/htdocs/wegone"
    
    <Directory "/usr/local/apache2/htdocs/wegone">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:8081>
    ServerName gundes.site.lan
    ServerAlias gundes.localhost
    DocumentRoot "/usr/local/apache2/htdocs/gundes"
    
    <Directory "/usr/local/apache2/htdocs/gundes">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

Listen 443

<VirtualHost *:443>
    ServerName wegone.site.lan
    ServerAlias wegone.localhost
    DocumentRoot "/usr/local/apache2/htdocs/wegone"

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/ssl/apache.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/ssl/apache.key"

    <Directory "/usr/local/apache2/htdocs/wegone">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>

<VirtualHost *:443>
    ServerName gundes.site.lan
    ServerName gundes.localhost
    DocumentRoot "/usr/local/apache2/htdocs/gundes"

    SSLEngine on
    SSLCertificateFile "/usr/local/apache2/conf/ssl/apache.crt"
    SSLCertificateKeyFile "/usr/local/apache2/conf/ssl/apache.key"

    <Directory "/usr/local/apache2/htdocs/gundes">
        AllowOverride All
        Require all granted
    </Directory>
</VirtualHost>
